-- crea la base de datos y la tabla
CREATE DATABASE IF NOT EXISTS practica CHARACTER SET utf8mb4;
USE practica;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  creado TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
